# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170118_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pbulished',
            new_name='published',
        ),
    ]
